### PR TITLE
Bias QCs now embedded in main code

### PR DESCRIPTION
**Pull request by thespacedoctor**
This PR also includes code to inject QCs into the FITS headers.

Here's an example of QCs reported in header of UVB master bias:

image

### CODE REVIEW

**Comment by thespacedoctor** [comment]
This PR is related to issue #73. @marcolandoni to review.

**Comment by thespacedoctor** [comment]
I've pushed dark QCs into this PR also now. NIR RON and median flux level in darks are now being calculated correctly and injected into the FITS headers.

Fixed an issue with raw bias RON calculations. RON is calculated on one raw bias frame subtracted from the next consecutive raw bias frame; this removed the bias level leaving only noise. However, this noise is increased by sqrt(2) due to the subtraction. So the calculation of noise on subtracted frame needs to be divided again by sqrt(2) to give the RON on a single raw bias frame.

**Comment by smarttgit** [comment]
Do you need to subtract one bias frame from another to calculate RON ? This will indeed increase noise by sort(2), but why not just calculate SDEV or variance just from a single frame ? The noise shouldn't be affected by the bias level ? Better to keep it as simple as possible rather than having to fix by introducing another factor. 

Also, if the bias frame used for subtraction has an anomalously large RON (due to some fault), it will propagate and leave RON in the subtracted frame >>sort(2) factor.  

Am I missing something, what's the reason for the subtraction ?

**Comment by smarttgit** [comment]
Yes, if a big ramp of structure on the bias then it would affect it if we are using full frame mode. 

I guess if ESO do it this way we should follow too.

**Pull request merged**
